### ISSUE TITLE
scoped CSS (deprecated) and the global "lang" attribute

### ISSUE THREAD

**Issue by kalbfled** [susanBuck/e28-fall20#33]
According to the [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style), the _scoped_ attribute for the `style` element is deprecated, but SFCs use it.  Might this become a problem?

I also noted that `<style lang="scss">` appears in App.vue for the ZipFoods example.  I haven't really used scss, so maybe this is a de-facto standard, but the global [lang attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) seems intended the specify a spoken language: English, French, etc.

**Comment by susanBuck** [comment]
Hi @kalbfled -

Good questions -

SFCs are converted by Vue loader (part of our build system) into the JS/HTML/CSS that the browser receives. By the time the browser sees the CSS, the `scoped` attribute has been removed.

More info here: https://vue-loader.vuejs.org/guide/scoped-css.html#scoped-css

Similar thing with the `lang` attribute - it's just information the SFC uses to understand how to parse our CSS, and is removed post-processing. 

To demonstrate the above points, here's a style block from the ZipFoods SFC (`App.vue`) that uses both `scoped` and `lang`:

```html
<style lang='scss' scoped>
@import '@/assets/scss/zipfoods.scss';
</style>
```

And here's the resulting file (in `/dist/css`) after we run the build system (`npm run dev`):

```css
[data-v-3bbf3846]{box-sizing:border-box}html[data-v-3bbf3846]{font-size:62.5%;color:#111;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;overflow-y:scroll}body[data-v-3bbf3846]{font-size:1.6rem;margin-bottom:60px}#app[data-v-3bbf3846]{max-width:800px;width:100%;margin:auto;padding-bottom:20px;text-align:center}header[data-v-3bbf3846]{text-align:center;margin-top:20px}#logo[data-v-3bbf3846]{width:318px}nav ul[data-v-3bbf3846]{list-style-type:none}nav ul li[data-v-3bbf3846]{display:inline-block}nav ul li a[data-v-3bbf3846]:active,nav ul li a[data-v-3bbf3846]:hover,nav ul li a[data-v-3bbf3846]:link,nav ul li a[data-v-3bbf3846]:visited{display:inline-block;text-transform:capitalize;padding:5px;margin:5px;cursor:pointer;color:#0074d9}nav ul li a[data-v-3bbf3846]:hover{background-color:#0074d9;color:#fff;text-decoration:none}nav ul li a.router-link-active[data-v-3bbf3846]:active,nav ul li a.router-link-active[data-v-3bbf3846]:hover,nav ul li a.router-link-active[data-v-3bbf3846]:link,nav ul li a.router-link-active[data-v-3bbf3846]:visited{text-decoration:none;color:#111;background-color:#fff;cursor:inherit}#products .product[data-v-3bbf3846]{width:75%;margin:auto;margin-bottom:20px;border:1px solid #000;padding:20px}#products .product .product-name[data-v-3bbf3846]{font-weight:700;font-size:2rem;margin:5px 0 10px 0}#products .product .product-thumb[data-v-3bbf3846]{width:200px}#products .product .product-description[data-v-3bbf3846]{width:75%;margin:auto;text-align:left;font-style:italic}#products .product .product-price[data-v-3bbf3846]{font-family:Georgia,Times New Roman,Times,serif;font-weight:700;font-size:2rem}#featured[data-v-3bbf3846]{background-color:#b2e9ff;border-radius:5px;padding:10px}#product-page img[data-v-3bbf3846]{width:200px}#product-page .description[data-v-3bbf3846],#product-page .price[data-v-3bbf3846]{font-size:2rem}#product-page button[data-v-3bbf3846]{display:block;margin:10px auto;font-size:2rem}.cleanList[data-v-3bbf3846]{list-style-type:none;padding:0}.alert[data-v-3bbf3846]{background-color:#2ecc40;color:#fff;border-radius:5px;font-weight:700;padding:5px;margin:5px}.fade-enter-active[data-v-3bbf3846],.fade-leave-active[data-v-3bbf3846]{transition:opacity .5s}.fade-enter[data-v-3bbf3846],.fade-leave-to[data-v-3bbf3846]{opacity:0}
```

Note how each selector has this new data attribute `[data-v-3bbf3846]` - that's how it accomplishes the scoped CSS - it adds this unique selector. Also, any SCSS syntax or reference to SCSS is not present.
